In [1]:
import numpy as np
l1 = np.array([2,3,4,5])
l2 =[]
for i in l1 :
    l2.append(i*i)

In [3]:
print(l2)

[4, 9, 16, 25]


In [5]:
# This is using vecterization operation 
result = l1 **2
print(result)

[ 4  9 16 25]


In [6]:
result +=10

In [7]:
print(result)

[14 19 26 35]


In [16]:
arr1 =np.array([1,2,3])
arr2 =np.array([10,20,30])
result = arr1 + arr2
print(result)

In [17]:
#arr4 dividing every row of arr3 means arr4 broadcasting every row in arr3
arr3 =np.array([[1,2,3],[4,5,6]])
arr4 =np.array([10,20,30])
result = arr3+arr4
print(result)

[[11 22 33]
 [14 25 36]]


In [19]:
# # Simulating a dataset (5 samples, 3 features)
# data = np.array([[10, 20, 30],
#                  [15, 25, 35],
#                  [20, 30, 40],
#                  [25, 35, 45],
#                  [30, 40, 50]])

# # Calculating mean and standard deviation for each feature (column)
# mean = data.mean(axis=0)
# std = data.std(axis=0)

# # Normalizing the data using broadcasting
# normalized_data = (data - mean) / std

# print(normalized_data)
data = np.array([[10,20,30],
                 [15,20,25],
                 [30,35,40],
                 [45,50,55]])
mean = data.mean(axis= 0)
std = data.std(axis = 0)
normalization_data = (data-mean)/std
print(normalization_data)

[[-1.09544512 -0.90453403 -0.65465367]
 [-0.73029674 -0.90453403 -1.09108945]
 [ 0.36514837  0.30151134  0.21821789]
 [ 1.46059349  1.50755672  1.52752523]]


In [9]:
Arr1 = np.array([1,2,3,4,5])
result = []
for i in Arr1:
    result.append(i ** 2)
print(result)

[1, 4, 9, 16, 25]
