In [2]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])#1D array
arr2 = np.array([[1,2,3,4],[1,2,3,4,]])#2D array
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3 4]
 [1 2 3 4]]


In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [12]:
np.eye((7))

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [16]:
np.arange(10,1,-2)

array([10,  8,  6,  4,  2])

In [24]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [23]:
np.linspace(2,0,5)

array([2. , 1.5, 1. , 0.5, 0. ])

In [27]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [71]:
A.size

12

In [72]:
A.shape

(4, 3)

In [73]:
A.ndim

2

In [52]:
A.dtype

dtype('int32')

In [53]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = 'float32')

In [54]:
print(A)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [55]:
A.dtype

dtype('float32')

In [36]:
x = A.astype('int32')

In [37]:
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
x.dtype

dtype('int32')

In [39]:
A.dtype

dtype('int32')

In [42]:
reshaped = A.reshape((4,3))

In [43]:
 print(reshaped)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [89]:
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [98]:
reshaped.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])