In [24]:
import numpy as np

In [25]:
arr = np.array([1,2,3,4,5])

In [26]:
print(arr.dtype)

int32


In [27]:
arr.astype("float64")

array([1., 2., 3., 4., 5.])

In [28]:
arr.dtype

dtype('int32')

In [29]:
arr2= np.array([1,2,3,4,5],dtype = "float64")
print(arr2.dtype)
print(arr2)

float64
[1. 2. 3. 4. 5.]


In [30]:
arr

array([1, 2, 3, 4, 5])

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr_large = np.array([20000,40000,500000],dtype = np.int64)
arr_large.dtype

dtype('int64')

In [33]:
arr_small = arr_large.astype(np.int32)

In [34]:
print(arr_small)

[ 20000  40000 500000]


In [35]:
print(arr_small.dtype)

int32


In [36]:
arr2.nbytes

40

In [37]:
arr.nbytes

20

In [38]:
#for finding memory usage 
arr_first = np.array([1,2,3,5,5],dtype = 'int64')
arr_second = np.array([6,7,8,9,10],dtype = 'int32')
print(arr_first.nbytes)
print(arr_second.nbytes)

40
20


In [39]:
#complex number 
arr_complex = np.array([1+4j,4+6j],dtype = 'complex128')
arr_complex

array([1.+4.j, 4.+6.j])

In [42]:
Arr = np.array([1+2j,2+3j,4+6j],dtype = 'complex64')

In [43]:
print(Arr)

[1.+2.j 2.+3.j 4.+6.j]


In [44]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)

[{'a': 1} list([1, 2, 3]) 'hello']
