In [2]:
import numpy as np

In [23]:
arry = np.array([[1,2,3,4,5],[10,20,30,40,50],[100,200,300,400,500]])

In [24]:
print(arry)

[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]


In [25]:
arry.shape

(3, 5)

In [56]:
#Convert the array into float [1.1,2.2,3.3]
# arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
# print(arr.dtype)  # float32

# arr_int = arr.astype(np.int32)  # Convert float to int
# print(arr_int)  # [1 2 3]


Arr2 = np.array([1.1,2.2,3.3])
Arr2 = Arr2.astype(dtype = "int32")
print(Arr2)
# print(Arr2)


[1 2 3]


In [71]:
arr3 = np.array([1,2,3,4,5,6])
idex  = arr3 [[1,3,5]]
idex

array([2, 4, 6])

In [75]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Reashaped_array = arr4.reshape((3,3))
print(Reashaped_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
Arr5 = np.array([45,23,54,65,87,81,12,24,53,90])
result = Arr5[Arr5>50]

In [80]:
print(result)

[54 65 87 81 53 90]
