In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(arr1.sum(axis = 0))
print(arr1.sum(axis = 1))

[12 15 18]
[ 6 15 24]


In [20]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
reshaped_array = arr.reshape((4,4))
print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
A = np.arange(16)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr1 [0: , 2:])

[[3]
 [6]
 [9]]


In [35]:
OneD_Array =np.random.randint(1,101,size = 10)
print(OneD_Array)

[56 50 44 59 52 57 13 80 54 57]


In [36]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [43]:
Z = np.array([43,46,76,31,53,65,7,90,23.65])
Mean = np.mean(Z)
Std_Deviation = np.std(Z)
print(Mean)
print(Std_Deviation)

48.294444444444444
24.61513134959927


In [47]:
Flatten = arr1.flatten()
print(Flatten)

[1 2 3 4 5 6 7 8 9]


In [49]:
p = np.array([1,3,4,5,1,3,5,2])
np.unique(p)

array([1, 2, 3, 4, 5])

In [51]:
Z[Z>30]

array([43., 46., 76., 31., 53., 65., 90.])

In [57]:
Arr1 = ([[1,2],[3,4]])
Arr2 = ([[5,6],[7,8]])
result = np.dot(Arr1,Arr2)
print(result)

[[19 22]
 [43 50]]
