In [2]:
import numpy as np 

In [46]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
arr[0][2]

3

In [49]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[12 15 18]
[ 6 15 24]


In [51]:
print(arr[2,1])

8


In [52]:
print(arr[0:2 ,1:3])

[[2 3]
 [5 6]]


In [53]:
print(arr.shape)

(3, 3)


In [3]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [4]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
arr[:,1,2]

array([ 6, 12])

In [61]:
arr.shape

(2, 2, 3)

In [80]:
print(arr[1,0,0])

7


In [97]:
print(arr[: , 1 , 1])

[ 5 12]


In [98]:
print(arr[:,0])

[[1 2 3]
 [7 8 9]]


In [101]:
print(arr[:,0,1])

[2 8]


In [115]:
arr[:,1,: ]= 0
print(arr)

[[[1 2 3]
  [0 0 0]]

 [[7 8 9]
  [0 0 0]]]


In [116]:
arr[: , 0 , :] = 0

In [117]:
arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [104]:
arr[: , 1 , :] = 0


In [105]:
arr

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])