In [2]:
# Numpy Common Use Mathmatical function
# np.mean(arr)
# np.std(arr)
# np.var(arr) for finding Variance
# np.min(arr)
# np.max(arr)
# np.sum(arr)
# np.diff(arr)
# np.prod(arr)
# np.median(arr)
# np.percentile(arr, 50)  # For the 50th percentile (median)
# np.argmin(arr)
# np.argmax(arr)
# np.corrcoef(arr1, arr2)
# np.unique(arr)
# np.cumsum(arr)
# np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
# np.log(arr)
# np.exp(arr)


In [37]:
import numpy as np
arr = np.array([1,22,12,64,3,32,5,1,3,1])
arr2 = np.array([2,43,64,1,4,5])

In [5]:
np.mean(arr)

26.2

In [7]:
np.std(arr)

21.525798475317934

In [8]:
np.var(arr)

463.35999999999996

In [9]:
np.max(arr)

64

In [10]:
np.min(arr)

1

In [11]:
np.sum(arr)

131

In [13]:
np.diff(arr)

array([ 21, -10,  52, -32])

In [15]:
np.prod(arr)

540672

In [16]:
np.median(arr)

22.0

In [17]:
np.percentile(arr,64)

27.6

In [18]:
np.argmin(arr)

0

In [19]:
np.argmax(arr)

3

In [24]:
np.corrcoef(arr,arr2)

array([[ 1.        , -0.38595294],
       [-0.38595294,  1.        ]])

In [29]:
np.unique(arr)

array([ 1,  3,  5, 12, 22, 32, 64])

In [30]:
np.cumsum(arr)

array([  1,  23,  35,  99, 131, 136, 137, 140, 141])

In [42]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
np.log(arr)

array([0.        , 3.09104245, 2.48490665, 4.15888308, 1.09861229,
       3.4657359 , 1.60943791, 0.        , 1.09861229, 0.        ])

In [35]:
np.exp(arr)

array([2.71828183e+00, 3.58491285e+09, 1.62754791e+05, 6.23514908e+27,
       2.00855369e+01, 7.89629602e+13, 1.48413159e+02, 2.71828183e+00,
       2.00855369e+01, 2.71828183e+00])