In [3]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[6,7,8],[9,10,11]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
arr[0]

array([1, 2, 3])

In [6]:
arr[3]

array([ 9, 10, 11])

In [7]:
flat = arr.flatten()

In [8]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [9]:
flat[9]

9

In [10]:
flat[4:5]

array([5])

In [11]:
flat[:5]

array([1, 2, 3, 4, 5])

In [12]:
flat[5:]

array([ 6,  6,  7,  8,  9, 10, 11])

In [13]:
flat[-1]

11

In [14]:
flat[::2]

array([ 1,  3,  5,  6,  8, 10])

In [14]:
flat[::3]

array([1, 4, 6, 9])

In [15]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [19]:
b = flat[3:8]
print(b)

[4 5 6 6 7]


In [20]:
b[0]

4

In [21]:
b[0] = 55667

In [22]:
print(b)

[55667     5     6     6     7]


In [23]:
print(flat)

[    1     2     3 55667     5     6     6     7     8     9    10    11]


In [24]:
b = flat[5:8].copy()#This is not a slicing because we are using copy method 
                    #insted of slicing so thatswhy the b memory size
                    #array is created


In [25]:
print(b)

[6 6 7]


In [26]:
print(flat)

[    1     2     3 55667     5     6     6     7     8     9    10    11]


In [27]:
b[0] = 53595

In [28]:
print(b)

[53595     6     7]


In [29]:
print(flat)

[    1     2     3 55667     5     6     6     7     8     9    10    11]


In [15]:
Array = np.array([10,20,30,40,50])

In [16]:
print(Array)

[10 20 30 40 50]


In [18]:
Array[[0,2,4]]

array([10, 30, 50])

In [19]:
Array[Array>30]

array([40, 50])